### ISSUE TITLE
have a problem when i test download ..

### ISSUE THREAD

**Issue by omer-rm** [burhanwakhid/flutter_speedtest#1]
its break in a middel of Progress .. 
I/flutter ( 6700): 6.567348558599999
I/flutter ( 6700): 6.56942657739588
I/flutter ( 6700): 6.571503430337409
I/flutter ( 6700): 6.572841798107273
I/flutter ( 6700): 6.5745476852479445
I/flutter ( 6700): 6.5762524251238235
I/flutter ( 6700): 6.577219034295064
I/flutter ( 6700): 6.577448179884551
I/flutter ( 6700): 6.57878144731558
I/flutter ( 6700): 6.584022199724104
I/flutter ( 6700): 6.588521960383693
I/flutter ( 6700): 6.590585929857385
I/flutter ( 6700): 6.593017194374088
I/flutter ( 6700): 6.594710409444793
I/flutter ( 6700): 6.591248762674767
I/flutter ( 6700): 6.59294011370075
I/flutter ( 6700): 6.593159548246598
I/flutter ( 6700): 6.594113663128771
I/flutter ( 6700): 6.594699555327335
I/flutter ( 6700): 6.595652081122112
I/flutter ( 6700): 6.596970909816326
I/flutter ( 6700): 6.5971875894969525
I/flutter ( 6700): 6.599914613553676
E/flutter ( 6700): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
E/flutter ( 6700): #0      _FutureListener.handleError (dart:async/future_impl.dart:181:7)
E/flutter ( 6700): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter ( 6700): #2      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter ( 6700): #3      Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 6700): #4      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter ( 6700): #5      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter ( 6700): #6      Future.any.onError (dart:async/future.dart:616:45)
E/flutter ( 6700): #7      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 6700): #8      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 6700): #9      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter ( 6700): #10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter ( 6700): #11     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter ( 6700): #12     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 6700): #13     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter ( 6700): #14     _rootRun (dart:async/zone.dart:1426:13)
E/flutter ( 6700): #15     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 6700): #16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 6700): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 6700): #18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 6700): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 6700):

**Comment by burhanwakhid** [comment]
Thanks for catching this!

I will working on it next week to fix this issue and update new method for speedtest library

**Comment by burhanwakhid** [comment]
please check on the latest version 🙏
